--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Sergittos/SkyWars
build-by-default: true
branches:
- master
projects:
  SkyWars:
    path: ""
    lint:
      phpstan: false
      syntaxError: false
...
